///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesMaxsip1logo = 'assets/images/maxsip1logo.png';
  static const String product1 = "assets/images/Isolated_white_t_shirt_with_hanger.jpg";
  static const String product2 = "assets/images/PngItem_434027.png";
  static const String errorPicture =  "assets/images/4503796.jpg";
}
